name: SonarCloud analysis
on:
  push:
    branches: [ "master", "release" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master", "release" ]
  workflow_dispatch:
permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RO_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=sftwnd_crayfish_common_functional
            -Dsonar.organization=sftwnd-github
